#!/usr/bin/env bash
#MISE description="Start Docker containers"
set -e

docker compose up -d

docker run \
  --network=pawatchat_default \
  --name wait \
  --rm dokku/wait  -c \
  rabbit:${RABBIT_PORT},\
  database:${DATABASE_PORT},\
  redis:${REDIS_PORT}
